---
apiVersion: v1
kind: Service
metadata:
  name: kind-golang-service
  labels:
    app: kind-golang
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: kind-golang
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kind-golang
  name: kind-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kind-golang
  template:
    metadata:latest
      labels:
        app: kind-golang
    spec:
      containers:
      - image: localhost:5000/kind_golang:latest
        name: kind-golang
        imagePullPolicy: Always
        ports:
          - protocol: TCP
            port: 8080
            targetPort: 8080